
version: '3.9'

services:
  account-api:
    build:
      context: .
      dockerfile: BankMore.Account/BankMore.Account.Api/Dockerfile
    ports:
      - "5000:8080"
    volumes:
      - ./data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/account.db
