services:
  oracle-xe:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe
    environment:
      - ORACLE_PASSWORD=bankmore123
    ports:
      - "1521:1521"

  accounts-api:
    build:
      context: .
      dockerfile: BankMore.Account/BankMore.Account.Api/Dockerfile
    depends_on:
      - oracle-xe
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__OracleConnection=User Id=bankmore;Password=bankmore123;Data Source=172.18.16.1:1521/XE
      - Jwt__Key=MinhaChaveSuperSecreta_1234567890!!
      - Jwt__Issuer=bankmore
      - Jwt__Audience=bankmore-client
      - Jwt__Expires=60
    ports:
      - "5001:8080"

  transfers-api:
    build:
      context: .
      dockerfile: BankMore.Transfer/BankMore.Transfer.Api/Dockerfile
    depends_on:
      - oracle-xe
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__OracleConnection=User Id=bankmore;Password=bankmore123;Data Source=172.18.16.1:1521/XE
      - AccountAPI__BaseAddress=http://accounts-api:8080/
      - Jwt__Key=MinhaChaveSuperSecreta_1234567890!!
      - Jwt__Issuer=bankmore
      - Jwt__Audience=bankmore-client
      - Jwt__Expires=60
    ports:
      - "5002:8080"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    networks:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
    networks:
      - kafka

  tariffs-worker:
    build:
      context: .
      dockerfile: BankMore.Tariff/BankMore.Tariff.Worker/Dockerfile
    depends_on:
      - kafka
      - oracle-xe
    environment:
      - ConnectionStrings__OracleConnection=User Id=bankmore;Password=bankmore123;Data Source=172.18.16.1:1521/XE
networks:
  kafka:
