// <auto-generated />
using System;
using BankMore.Transfer.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace BankMore.Transfer.Infrastructure.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankMore.Transfer.Domain.Entities.Transferencia", b =>
                {
                    b.Property<string>("IdTransferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR2(37)");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("IdContaCorrenteDestino")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(37)");

                    b.Property<string>("IdContaCorrenteOrigem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(37)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("NUMBER(12,2)");

                    b.HasKey("IdTransferencia");

                    b.ToTable("TRANSFERENCIA", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
