apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfers-api
  namespace: bankmore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfers-api
  template:
    metadata:
      labels:
        app: transfers-api
    spec:
      containers:
        - name: transfers-api
          image: bankmore-transfers-api:latest
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:8080
            - name: ConnectionStrings__OracleConnection
              value: User Id=system;Password=admin;Data Source=172.18.16.1:1521/XE
            - name: AccountAPI__BaseAddress
              value: http://accounts-api:8080/
            - name: Jwt__Key
              value: MinhaChaveSuperSecreta_1234567890!!
            - name: Jwt__Issuer
              value: bankmore
            - name: Jwt__Audience
              value: bankmore-client
            - name: Jwt__Expires
              value: "60"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: transfers-api
  namespace: bankmore
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: transfers-api