apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfers-api
  namespace: bankmore
  labels:
    app: transfers-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transfers-api
  template:
    metadata:
      labels:
        app: transfers-api
    spec:
      containers:
      - name: bankmore-transfers-api
        image: bankmore-transfers-api:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: transfers-service
  namespace: bankmore
spec:
  selector:
    app: transfers
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP