apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-db
  template:
    metadata:
      labels:
        app: oracle-db
    spec:
      containers:
        - name: oracle-db
          image: gvenzl/oracle-xe:21-slim
          ports:
            - containerPort: 1521
          env:
            - name: ORACLE_PASSWORD
              value: "bankmore123"
---
apiVersion: v1
kind: Service
metadata:
  name: oracle-db
spec:
  type: ClusterIP
  selector:
    app: oracle-db
  ports:
    - port: 1521
      targetPort: 1521