apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-api
  namespace: bankmore
  labels:
    app: accounts-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounts-api
  template:
    metadata:
      labels:
        app: accounts-api
    spec:
      containers:
      - name: bankmore-accounts-api
        image: bankmore-accounts-api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  namespace: bankmore
spec:
  selector:
    app: accounts
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP