// <auto-generated />
using System;
using BankMore.Account.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace BankMore.Account.Infrastructure.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20251003014211_Account_Movement_Idempotency")]
    partial class Account_Movement_Idempotency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankMore.Account.Domain.Entities.ContaCorrente", b =>
                {
                    b.Property<string>("IdContaCorrente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR2(37)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("Numero")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.HasKey("IdContaCorrente");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("CONTACORRENTE", (string)null);
                });

            modelBuilder.Entity("BankMore.Account.Domain.Entities.Idempotencia", b =>
                {
                    b.Property<string>("ChaveIdempotencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR2(37)")
                        .HasColumnName("Chave_Idempotencia");

                    b.Property<string>("Requisicao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)");

                    b.HasKey("ChaveIdempotencia");

                    b.ToTable("IDEMPOTENCIA", (string)null);
                });

            modelBuilder.Entity("BankMore.Account.Domain.Entities.Movimento", b =>
                {
                    b.Property<string>("IdMovimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NVARCHAR2(37)");

                    b.Property<DateTime>("DataMovimento")
                        .HasMaxLength(25)
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("IdContaCorrente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(37)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("TipoMovimento")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("NUMBER(12,2)");

                    b.HasKey("IdMovimento");

                    b.HasIndex("IdContaCorrente");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.ToTable("MOVIMENTO", (string)null);
                });

            modelBuilder.Entity("BankMore.Account.Domain.Entities.Movimento", b =>
                {
                    b.HasOne("BankMore.Account.Domain.Entities.ContaCorrente", "ContaCorrente")
                        .WithMany("Movimentos")
                        .HasForeignKey("IdContaCorrente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaCorrente");
                });

            modelBuilder.Entity("BankMore.Account.Domain.Entities.ContaCorrente", b =>
                {
                    b.Navigation("Movimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
