// <auto-generated />
using System;
using BankMore.Account.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace BankMore.Account.Infrastructure.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankMore.Account.Domain.Entities.ContaCorrente", b =>
                {
                    b.Property<byte[]>("IdContaCorrente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasKey("IdContaCorrente");

                    b.ToTable("CONTACORRENTE", (string)null);
                });

            modelBuilder.Entity("BankMore.Account.Domain.Entities.Idempotencia", b =>
                {
                    b.Property<string>("Chave_Idempotencia")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Requisicao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Chave_Idempotencia");

                    b.ToTable("IDEMPOTENCIA", (string)null);
                });

            modelBuilder.Entity("BankMore.Account.Domain.Entities.Movimento", b =>
                {
                    b.Property<byte[]>("IdMovimento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<byte[]>("IdContaCorrente")
                        .IsRequired()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("TipoMovimento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(1)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("IdMovimento");

                    b.HasIndex("IdContaCorrente");

                    b.ToTable("MOVIMENTO", (string)null);
                });

            modelBuilder.Entity("BankMore.Account.Domain.Entities.Tarifa", b =>
                {
                    b.Property<byte[]>("IdTarifa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<byte[]>("IdContaCorrente")
                        .IsRequired()
                        .HasColumnType("RAW(16)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("IdTarifa");

                    b.HasIndex("IdContaCorrente");

                    b.ToTable("TARIFA", (string)null);
                });

            modelBuilder.Entity("BankMore.Account.Domain.Entities.Transferencia", b =>
                {
                    b.Property<byte[]>("IdTransferencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("DataMovimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<Guid>("IdContaCorrenteDestino")
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("IdContaCorrenteOrigem")
                        .HasColumnType("RAW(16)");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("IdTransferencia");

                    b.ToTable("TRANSFERENCIA", (string)null);
                });

            modelBuilder.Entity("BankMore.Account.Domain.Entities.Movimento", b =>
                {
                    b.HasOne("BankMore.Account.Domain.Entities.ContaCorrente", "ContaCorrente")
                        .WithMany("Movimentos")
                        .HasForeignKey("IdContaCorrente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaCorrente");
                });

            modelBuilder.Entity("BankMore.Account.Domain.Entities.Tarifa", b =>
                {
                    b.HasOne("BankMore.Account.Domain.Entities.ContaCorrente", "ContaCorrente")
                        .WithMany("Tarifas")
                        .HasForeignKey("IdContaCorrente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaCorrente");
                });

            modelBuilder.Entity("BankMore.Account.Domain.Entities.ContaCorrente", b =>
                {
                    b.Navigation("Movimentos");

                    b.Navigation("Tarifas");
                });
#pragma warning restore 612, 618
        }
    }
}
